server {
	listen 1024;
	listen [::]:1024;

	root /var/www/transcendance;
	index index.html index.htm;

	server_name transcendance;

	location /backend/{
		proxy_pass http://backend:4000/;
	}
	location / {
		proxy_pass http://frontend:3000/;
	}
}